# Params
[Params]
navBrand = 'WebDong.dev'
navBrandShort = 'WebDong'

brand = 'Triangle Dong Dong'
brandtc = 'ä¸‰è§’æ±æ±'
brandLogo = 'â—¢â—¢â—¢'
brandUrl = 'https://www.tridong.com/'
brandUrlShort = 'tridong.com'
brandEmail = 'triangledongdong@gmail.com'
brandPhone = '09-3636-1996'
brandLocation = 'No. 129, Section 3, Sanmin Rd, North District, Taichung City, 404'
brandLocationtc = 'è‡ºä¸­å¸‚åŒ—å€ä¸‰æ°‘è·¯ä¸‰æ®µ129è™Ÿ'
brandWorktime = 'ç‡Ÿæ¥­æ™‚é–“ 9:30am - 18:30pm'

googleAnalytics = 'G-S6W57VD15P'

brandYoutube = 'https://www.youtube.com/channel/UCIFYY0VUOND2tBdC2YDpKkQ'
brandInstagram = 'https://www.instagram.com/triangle_dongdong'
brandBehance = 'https://www.behance.net/triangledongdong2020'

slogan = "å°ˆæ¥­çš„è§’åº¦æœ‰è¶£åœ°ç©è¨­è¨ˆ"
brandDescription = "å‰µç«‹æ–¼2020å¹´ï¼Œä¸‰è§’æ±æ± Triangle Dong Dong æ˜¯ä¸€å€‹å°ˆæ³¨æ–¼å“ç‰Œè¨­è¨ˆçš„æ–°å‰µè¨­è¨ˆå…¬å¸ã€‚ "

utteranceRepo = "riceball-tw/Dong"
utteranceIssueTerm = "pathname"
utteranceLabel = "ğŸ’¬"
utteranceTheme = "github-light"



testimg = 'https://ucarecdn.com/16d84bf3-b31e-4a87-a82a-566364a85030/'

# Pagination
paginate = 10
PaginatePath = ""

imgsm = '-/smart_resize/300x300/'
imgmd = '-/smart_resize/600x600/'
imglg = '-/smart_resize/900x900/'
imgxl = '-/smart_resize/1200x1200/'

imgResize = '-/smart_resize/'
imgAuto = '-/format/auto/'

imgProgress = '-/progressive/yes/'

cloudinaryImg = "https://res.cloudinary.com/tridong/image/upload"
cloudinaryVideo = ""

# Navbar
[menu]
[[menu.main]]
  # Identifier must match the section name
  identifier = 'home'
  name = 'é¦–é '
  title = 'ä¸‰è§’æ±æ±é¦–é '
  url = '/'
  weight = 1
[[menu.main]]
  identifier = 'about'
  name = 'é—œæ–¼'
  title = 'é—œæ–¼ä¸‰è§’æ±æ±'
  url = '/about/'
  weight = 2
[[menu.main]]
  identifier = 'post'
  name = 'æ–‡ç« '
  title = 'æŸ¥çœ‹éƒ¨è½æ ¼æ–‡ç« '
  url = '/post/'
  weight = 3
[[menu.main]]
  identifier = 'project'
  name = 'å°ˆæ¡ˆ'
  title = 'æŸ¥çœ‹å°ˆæ¡ˆä½œå“'
  url = '/Project/'
  weight = 4

# Sitemap
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# Taxonomy
[taxonomies]
  category = "category"
  tag = "tag"
  project = "project"

baseURL = '/'
languageCode = 'en-us'


# Markup Engine
enableEmoji = true
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4


  [markup.tableOfContents]
    endLevel = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true





[server]
[[server.headers]]
  for = '/*'
  [server.headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "'default-src' 'self' data: 'unsafe-eval' 'unsafe-inline' www.google-analytics.com www.googletagmanager.com https://i.imgur.com https://res.cloudinary.com www.youtube-nocookie.com www.youtube.com "